# Header metadata
url: soniawarzynska.com

author: Sonia Warzyńska

description_pl: Solistka Sonia Warzyńska - sopran. Oficjalna strona artystki.
description_en: Soloist Sonia Warzyńska - soprano. Official website of the artist.

og_site_name_pl: Sonia Warzyńska - sopran
og_site_name_en: Sonia Warzyńska - soprano

# Social media
social:
  facebook: https://facebook.com/SoniaWarzynskaSopran
  gplus   : https://plus.google.com/+SoniaWarzynskaSopran
  twitter : https://twitter.com/sonia_warzynska
  youtube : https://youtube.com/SoniaWarzynskaSopran
  
  
# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Europe/Warsaw

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink: /:title/

# Struktura galerii
gallery:
  "bukowno2014":
    "title":
      "pl": "Bukowno"
      "en": "Bukowno"
    "desc":
      "pl": "Koncert w Miejskim Ośrodku Kultury w Bukownie, 14.11.2014r. Wraz z Sylwią Frączek (sopran) i Aleksandrem Bardasau (baryton)"
      "en": "Concert in Municipal Cultural Centere in Bukowno with Sylwia Frączek (soprano) and Aleksandr Bardasau (baritone), 14.11.2014."
    "images":
      "01": "bukowno1"	
      "02": "bukowno2"	
      "03": "bukowno3"	
      "04": "bukowno4"	
      "05": "bukowno5"	
      "06": "bukowno6"	
      "07": "bukowno7"	
      "08": "bukowno8"	

  "tarnobrzeg":
    "title":
      "pl": "Tarnobrzeg"
      "en": "Tarnobrzeg"
    "desc":
      "pl": "Jubileusz 40-lecia Państwowej Szkoły Muzycznej w Tarnobrzegu 27.10.2014r"
      "en": "Tarnobrzeg 27.10.2014r"
    "images":
      "01": "tarnobrzeg1"	
      "02": "tarnobrzeg2"	
      "03": "tarnobrzeg3"

  "wroclaw":
    "title":
      "pl": "Platinum Palace Wrocław"
      "en": "Platinum Palace Wrocław"
    "desc":
      "pl": "Koncert w ramach Aukcji Młodej Sztuki III, Platinum Palace we Wrocławiu, 18.10.2014r."
      "en": "Platinum Palace Wrocław, 18.20.2014r."
    "images":
      "01": "wroclaw1"	
      "02": "wroclaw2"

  "baranowska":
    "title":
      "pl": "Sesja fotograficzna 2014"
      "en": "Photo session"
    "desc":
      "pl": "fot. Zofia Baranowska"
      "en": "by Zofia Baranowska"
    "images":
      "01": "baranowska1"	
      "02": "baranowska2"
      "03": "baranowska3"

  "estivales2014":
    "title":
      "pl": "Estivales En Puisaye 2014"
      "en": "Estivales En Puisaye 2014"
    "desc":
      "pl": "II sopran w “Mszy c-moll” Mozarta, 23-24.08.2014r. Briare, Toucy (Francja)"
      "en": "2nd soprano in “Mass in c minor” by Mozart, 23-24.08.2014. Briare, Toucy (France)"
    "images":
      "01": "estivales1"

  "impressioart":
    "title":
      "pl": "Impressio Art Sopot 2014"
      "en": "Impressio Art Sopot 2014"
    "desc":
      "pl": "VI Ogólnopolski Konkurs Wokalny Impressio Art Sopot 2014"
      "en": "6th Countrywide Vocal Competition Impressio Art Sopot 2014"
    "images":
      "01": "impressioart1"
      "02": "impressioart2"
      "03": "impressioart3"
      "04": "impressioart4"
      "05": "impressioart5"
      "06": "impressioart6"

  "wroclawd":
    "title":
      "pl": "Koncert u Dominikanów we Wrocławiu"
      "en": "Concert at the Dominican Monastery in Wrocław"
    "desc":
      "pl": "Koncert u Dominikanów we Wrocławiu, 17.07.2014"
      "en": "Concert at the Dominican Monastery in Wrocław, 17.07.2014"
    "images":
      "01": "wroclawd1"
      "02": "wroclawd2"
      "03": "wroclawd3"

  "figaro":
    "title":
      "pl": "Wesele Figara"
      "en": "“Le Nozze di Figaro”"
    "desc":
      "pl": "W.A.Mozart “Wesele Figara”. Spektakl odbył się w Operze Krakowskiej 22.05.2014r. Rola Zuzanny."
      "en": "W.A.Mozart “Le Nozze di Figaro“. Spectacle took place at the Opera House in Cracow. 22.05.2014. The Role of Susanna."
    "images":
      "02": "figaro2"
      "04": "figaro4"
      "07": "figaro7"
      "08": "figaro8"
      "09": "figaro9"
      "10": "figaro10"
      "11": "figaro11"
      "12": "figaro12"
      "13": "figaro13"
      "14": "figaro14"
      "15": "figaro15"

  "rodelinda":
    "title":
      "pl": "Rodelinda"
      "en": "Rodelinda"
    "desc":
      "pl": "Georg Friedrich Händel “Rodelinda”. Spektakl studencki, który odbył się 21.04.2013r. w Akademii Muzycznej w Krakowie. Tytułowa partia."
      "en": "Georg Friedrich Händel “Rodelinda”. Student's performance, which took place on 21.04.2013 at the Academy of Music in Cracow. Title role."
    "images":
      "01": "rodelinda1"
      "02": "rodelinda2"
      "03": "rodelinda3"
      "04": "rodelinda4"
      "05": "rodelinda5"
      "06": "rodelinda6"
      "07": "rodelinda7"
      "08": "rodelinda8"
      "09": "rodelinda9"
      "10": "rodelinda10"
      "11": "rodelinda11"
      "12": "rodelinda12"
      "13": "rodelinda13"
      
  "bukowno":
    "title":
      "pl": "Koncert w Bukownie"
      "en": "Concert in Bukowno"
    "desc":
      "pl": "Koncert odbył się w Miejskim Ośrodku Kultury w Bukownie 11.05.2013r."
      "en": "Concert took place in Municipal Cultural Centre in Bukowno, 11.05.2013"
    "images":
      "01": "bukowno1"	
      "02": "bukowno2"	
      "03": "bukowno3"	
      "04": "bukowno4"	
      "05": "bukowno5"	
      "06": "bukowno6"	
      "07": "bukowno7"


# Repertuar
repertoire:
  "parts":
    "title":
      "pl": Partie
      "en": Parts
    "items":
      "01":
        "en": "W.A.Mozart „Le Nozze di Figaro”: Susanna"
        "pl": "W.A.Mozart „Wesele Figara„: Zuzanna"
      "02":
        "en": "G.F.Händel „Rodelinda”: Rodelinda"
        "pl": "G.F.Händel „Rodelinda”: Rodelinda"
      "03":
        "en": "H.Purcell „The Fairyqueen”: Nyph, Night"
        "pl": "H.Purcell „The Fairyqueen”: Nyph, Night"
      "04":
        "en": "W.A.Mozart „Requiem in d minor”"
        "pl": "W.A.Mozart „Requiem d-moll”"
      "05":
        "en": "W.A.Mozart „Messe in c minor”"
        "pl": "W.A.Mozart „Msza c-moll”"
      "06":
        "en": "J.Haydn „Missa in augustiis”"
        "pl": "J.Haydn „Msza nelsońska”"

  "arias":
    "title":
      "pl": Arie
      "en": Arias
    "items":
      "01":  
          "en": "L.Arditi „Il bacio”"
          "pl": "L.Arditi „Il bacio”"
      "02":
          "en": "J.S.Bach “Heute noch” from “Kaffeekantate”"
          "pl": "J.S.Bach “Heute noch” z “Kantaty o kawie”"
      "03":
          "en": "V.Bellini „Eccomi in lieta vesta... Oh, quante volte...” from “Capuleti e i Montecchi” (Julia)"
          "pl": "V.Bellini „Eccomi in lieta vesta... Oh, quante volte...” z opery “Capuleti e i Montecchi” (Julia)"
      "04":
          "en": "G.Bizet “Me voilà seule dans la nuit... Comme autrefois...” from “Les pêcheurs de perles” (Leila)"
          "pl": "G.Bizet “Me voilà seule dans la nuit... Comme autrefois...” z opery “Poławiacze Pereł” (Leila)"
      "05":
          "en": "G.Caccini “Amarilli, mia bella”"
          "pl": "G.Caccini “Amarilli, mia bella”"
      "06":
          "en": "P.Czajkowski “Отчего это прежде не знала” from “Iolanta” (Iolanta)"
          "pl": "P.Czajkowski “Отчего это прежде не знала” z op. “Iolanta” (Iolanta)"
      "07":
          "en": "G.Donizetti „Il faut partir” from „La fille du régiment” (Maria)"
          "pl": "G.Donizetti „Il faut partir” z opery „Córka pułku” (Maria)"
      "08":        
          "en": "G.Donizetti „Salut a la France” from „La fille du régiment” (Maria)"
          "pl": "G.Donizetti „Salut a la France” z opery „Córka pułku” (Maria)"
      "09":
          "en": "G.Donizetti “Quel guardo il cavaliere... So anch’io...” from “Don Pasquale” (Norina)"
          "pl": "G.Donizetti “Quel guardo il cavaliere... So anch’io...” z opery “Don Pasquale” (Norina)"
      "10":
          "en": "G.Donizetti “Regnava nel silenzio... Quando rapito in estasi...” from “Lucia di Lammermoor” (Lucia)"
          "pl": "G.Donizetti “Regnava nel silenzio... Quando rapito in estasi...” z opery “Łucja z Lammermoor” (Łucja)"
      "11":
          "en": "A.Dvořak “Měsičku na nebe hlubokem” from “Rusalka” (Rusalka)"
          "pl": "A.Dvořak “Měsičku na nebe hlubokem” z opery “Rusałka” (Rusałka)"
      "12":
          "en": "J.Haydn „Infelice sventurata” from „I due supposti Conti” (Beatrice)"
          "pl": "J.Haydn „Infelice sventurata” z opery „I due supposti Conti” (Beatrycze)"
      "13":
          "en": "G.F.Händel „Tornami z vagheggiar” from „Alcina” (Morgana)"
          "pl": "G.F.Händel „Tornami z vagheggiar” z opery „Alcina” (Morgana)"
      "14":
          "en": "G.F.Händel „Piangeró la sorte mia” from „Giulio Cesare” (Cleopatra)"
          "pl": "G.F.Händel „Piangeró la sorte mia” z opery „Juliusz Cezar” (Kleopatra)"
      "15":
          "en": "G.F.Händel „Lascia ch’io pianga” from „Rinaldo”"
          "pl": "G.F.Händel „Lascia ch’io pianga” z opery „Rinaldo”"
      "16":
          "en": "K.Kurpiński „Wiek kwiecisty prędko płynie...” from „Leśniczy z Kozienickiej Puszczy” (Zośka)"
          "pl": "K.Kurpiński „Wiek kwiecisty prędko płynie...” z opery „Leśniczy z Kozienickiej Puszczy” (Zośka)"
      "17":
          "en": "K.Kurpiński „Spojrzenia tkliwe, uczucia żywe...” from „Czaromysł” (Wandala)"
          "pl": "K.Kurpiński „Spojrzenia tkliwe, uczucia żywe...” from „Czaromysł” (Wandala)"
      "18":
          "en": "J.Massenet „Obêissons quand leur voix appelle” from „Manon” (Manon)"
          "pl": "J.Massenet „Obêissons quand leur voix appelle” z opery „Manon” (Manon)"
      "19":
          "en": "W.A.Mozart „Ach, ich fühl’s” from „Die Zauberflöte” (Pamina)"
          "pl": "W.A.Mozart „Ach, ich fühl’s” z opery „Czarodziejski flet” (Pamina)"
      "20":
          "en": "W.A.Mozart „Vedrai, carino” from „Don Giovanni” (Zerlina)"
          "pl": "W.A.Mozart „Vedrai, carino” z opery „Don Giovanni” (Zerlina)"
      "21":
          "en": "W.A.Mozart “Giunse alfin il momento... Deh, vieni, non tardar...” from “Le Nozze di Figaro” (Susanna)"
          "pl": "W.A.Mozart “Giunse alfin il momento... Deh, vieni, non tardar...” z opery “Wesele Figara” (Zuzanna)"
      "22":
          "en": "W.A.Mozart “Venite inginocchiatevi” from “Le Nozze di Figaro” (Susanna)"
          "pl": "W.A.Mozart “Venite inginocchiatevi” z opery “Wesele Figara” (Zuzanna)"
      "23":
          "en": "G.Puccini „O mio babbino caro” from „Gianni Schicchi” (Lauretta)"
          "pl": "G.Puccini „O mio babbino caro” z opery „Gianni Schicchi” (Lauretta)"
      "24":
          "en": "M.Rimski-Korsakow „С подружками по ягоду ходить” from „Снегурочка” (Снегурочка)"
          "pl": "M.Rimski-Korsakow „С подружками по ягоду ходить” z opery „Snieguroczka” (Snieguroczka)"
      "25":
          "en": "G.Verdi „Gualtier Maldè... Caro nome...” from “Rigoletto” (Gilda)"
          "pl": "G.Verdi „Gualtier Maldè... Caro nome...” z opery “Rigoletto” (Gilda)"
      "26":
          "en": "G.Verdi „Tutte le feste” from „Rigoletto” (Gilda)"
          "pl": "G.Verdi „Tutte le feste” z opery „Rigoletto” (Gilda)"
      "27":
          "en": "C.M. von Weber „Kommt ein schlanken...” from “Der Freischütz” (Ännchen)"
          "pl": "C.M. von Weber „Kommt ein schlanken...” z opery “Wolny strzelec” (Anusia)"
      "28":
          "en": "W.Żeleński „Tam orzeł na turniami...” from „Janek” (Bronka)"
          "pl": "W.Żeleński „Tam orzeł na turniami...” z opery „Janek” (Bronka)"

  "sacred":
    "title":
      "pl": Arie Sakralne
      "en": Sacred Arias
    "items":
      "01":
        "en": "G.B.Pergolesi „Vidit suum” from „Stabat mater”"
        "pl": "G.B.Pergolesi „Vidit suum” z oratorium „Stabat mater”"
      "02":  
        "en": "J.S.Bach „Quia respexit” from „Magnificat”"
        "pl": "J.S.Bach „Quia respexit” z „Magnificat”"
      "03":  
        "en": "J.S.Bach „Er hat uns allen wohlgetan... Aus Liebe will mein Heiland sterben” from “Die Matthäus-Passion”"
        "pl": "J.S.Bach „Er hat uns allen wohlgetan... Aus Liebe will mein Heiland sterben” z “Pasji wg św.Mateusza”"
      "04":  
        "en": "J.Haydn “Nun beut die Flur das frische Grün” from “Die Schöpfung” (Gabriel)"
        "pl": "J.Haydn “Nun beut die Flur das frische Grün” z oratorium “Stworzenie świata” (Gabriel)"

  "songs":
    "title":
      "pl": Pieśni
      "en": Songs
    "items":  
      "01":  
        "en": "S.Barber „Puisque tout passe”"
        "pl": "S.Barber „Puisque tout passe”"
      "02":  
        "en": "F.Chopin „Piosnka litewska”"
        "pl": "F.Chopin „Piosnka litewska”"
      "03":  
        "en": "F.Chopin „Poseł”"
        "pl": "F.Chopin „Poseł”"
      "04":  
        "en": "F.Chopin „Wiosna”"
        "pl": "F.Chopin „Wiosna”"
      "05":  
        "en": "C.Debussy „Nuit d’étoiles”"
        "pl": "C.Debussy „Nuit d’étoiles”"
      "06":  
        "en": "E.Granados “El majo discreto”"
        "pl": "E.Granados “El majo discreto”"
      "07":  
        "en": "R.Hahn „Si mes vers avaient des ailes”"
        "pl": "R.Hahn „Si mes vers avaient des ailes”"
      "08":  
        "en": "M.Karłowicz “Rdzawe liście”"
        "pl": "M.Karłowicz “Rdzawe liście”"
      "09":  
        "en": "F.Liszt „Oh, quand je dors”"
        "pl": "F.Liszt „Oh, quand je dors”"
      "10":  
        "en": "F.Maklakiewicz “A jeśli chcesz zapomnieć”"
        "pl": "F.Maklakiewicz “A jeśli chcesz zapomnieć”"
      "11":  
        "en": "F.Maklakiewicz “Kocham Cię”"
        "pl": "F.Maklakiewicz “Kocham Cię”"
      "12":  
        "en": "S.Moniuszko “Dumka”"
        "pl": "S.Moniuszko “Dumka”"
      "13":  
        "en": "S.Moniuszko „Złota rybka”"
        "pl": "S.Moniuszko „Złota rybka”"
      "14":  
        "en": "S.Niewiadomski „Otwórz, Janku”"
        "pl": "S.Niewiadomski „Otwórz, Janku”"
      "15":  
        "en": "S.Niewiadomski „Śmieją się złote łany”"
        "pl": "S.Niewiadomski „Śmieją się złote łany”"
      "16":  
        "en": "F.Nowowiejski „Pieśń miłosna”"
        "pl": "F.Nowowiejski „Pieśń miłosna”"
      "17":  
        "en": "I.J.Paderewski „Gdy ostatnia róża zwiędła” from „4 Songs to Poems by Adam Asnyk”"
        "pl": "I.J.Paderewski „Gdy ostatnia róża zwiędła” z cyklu „4 pieśni do tekstów Asnyka”"
      "18":  
        "en": "I.J.Paderewski „Lune froide” from „12 Songs to Poems by Catulle Mendès”"
        "pl": "I.J.Paderewski „Lune froide” z cyklu „12 pieśni do słów Mendèsa”"
      "19":  
        "en": "I.J.Paderewski „Moja pieszczotka” from „6  Songs to Poems by Adam Mickiewicz”"
        "pl": "I.J.Paderewski „Moja pieszczotka” z cyklu „6 pieśni do słów Mickiewicza”"
      "20":  
        "en": "I.J.Paderewski „Nad wodą wielką i czystą” from „6 Songs to Poems by Adam Mickiewicz”"
        "pl": "I.J.Paderewski „Nad wodą wielką i czystą” z cyklu „6 pieśni do słów Mickiewicza”"
      "21":  
        "en": "I.J.Paderewski „Ton coeur est d’or pur” from „12 Songs to Poems by Catulle Mendès”"
        "pl": "I.J.Paderewski „Ton coeur est d’or pur” z cyklu „12 pieśni do słów Mendèsa”"
      "22":  
        "en": "P.Perkowski „Uty japońskie” (the whole cycle)"
        "pl": "P.Perkowski „Uty japońskie” (cały cykl)"      
      "23":  
        "en": "A.Rubinstein „Ночь”"
        "pl": "A.Rubinstein „Ночь”"
      "24":  
        "en": "S.Rachmaninow „Полюбилая”"
        "pl": "S.Rachmaninow „Полюбилая”"
      "25":  
        "en": "S.Rachmaninow „Здесь хорошо”"
        "pl": "S.Rachmaninow „Здесь хорошо”"
      "26":  
        "en": "R.Schumann “Das Lied der Suleika” from „Liederkreis”"
        "pl": "R.Schumann “Das Lied der Suleika” z cyklu „Liederkreis”"
      "27":  
        "en": "R.Schumann „Die Lotosblume” from „Liederkreis”"
        "pl": "R.Schumann „Die Lotosblume” z cyklu „Liederkreis”"
      "28":  
        "en": "R.Schumann „Mondnacht” from „Liederkreis”"
        "pl": "R.Schumann „Mondnacht” z cyklu „Liederkreis”"
      "29":  
        "en": "J.Szulc „Claire de lune”"
        "pl": "J.Szulc „Claire de lune”"
      "30":  
        "en": "K.Szymanowski “ Christkindleins Wiegenlied”"
        "pl": "K.Szymanowski “Kołysanka Dzieciątka Jezus”"
      "31":  
        "en": "K.Szmanowski „Zielone słowa”"
        "pl": "K.Szmanowski „Zielone słowa”"
      "32":  
        "en": "W.Żeleński „Blada róża”"
        "pl": "W.Żeleński „Blada róża”"

  "duets":
    "title":
      "pl": Duety
      "en": Duets
    "items":  
      "01":  
        "en": "P.Czajkowski „Final scene” from „Eugene Oniegin”"
        "pl": "P.Czajkowski Scena finałowa z op. „Eugeniusz Oniegin”"
      "02":  
        "en": "L.Delibes “Flower Duet” from. „Lakmé”"
        "pl": "L.Delibes duet kwiatów z op. „Lakmé”"
      "03":  
        "en": "W.A.Mozart Susanna&Conte duet “Crudel, perchè finora” from „Le Nozze di Figaro”"
        "pl": "W.A.Mozart duet Zuzanny i Hrabiego “Crudel, perchè finora” z op. „Wesele Figara”"
      "04":  
        "en": "W.A.Mozart Susanna&Figaro duet „Cinque, dieci” from „Le Nozze di Figaro”"
        "pl": "W.A.Mozart duet Zuzanny i Figara „Cinque, dieci” z op. „Wesele Figara”"
      "05":  
        "en": "W.A.Mozart Susanna&Figaro duet „Se a caso madama” from „Le Nozze di Figaro”"
        "pl": "W.A.Mozart duet Zuzanny i Figara „Se a caso madama” z op. „Wesele Figara”"
      "06":  
        "en": "W.A.Mozart Susanna&Marcellina duet „Via resti servita” from „Le Nozze di Figaro”"
        "pl": "W.A.Mozart duet Zuzanny i Marcelliny „Via resti servita” z op. „Wesele Figara”"
      "07":  
        "en": "W.A.Mozart Susanna&Contessa duet „Sull’aria” from „Le Nozze di Figaro”"
        "pl": "W.A.Mozart duet Zuzanny i Hrabiny „Sull’aria” z op. „Wesele Figara”"
      "08":  
        "en": "W.A.Mozart Zerlina&Don Giovanni duet „La ci darem la mano” from „Don Giovanni”"
        "pl": "W.A.Mozart duet Zerliny i Don Giovanniego „La ci darem la mano” z op. „Don Giovanni”"
      "09":  
        "en": "W.A.Mozart Annius&Servillia duet „Ah, perdona al primo affetto” from “Clemenza di Tito”"
        "pl": "W.A.Mozart duet Anniusa i Servilii „Ah, perdona al primo affetto” z op. „Łaskawość Tytusa”"
      "10":  
        "en": "G.Rossini “Cat’s Duet”"
        "pl": "G.Rossini duet kotów"
      "11":  
        "en": "G.Rossini duet „La regata veneziana”"
        "pl": "G.Rossini duet „La regata veneziana”"
      "12":  
        "en": "G.Verdi Violetta&Germont duet „Madamigella Valery...” from “Traviata”"
        "pl": "G.Verdi Violetta&Germont duet „Madamigella Valery...” from “Traviata”"

  "others":
    "title":
      "pl": Inne
      "en": Others
    "items":  
      "01":  
        "en": "L.Dalla „Caruso”"
        "pl": "L.Dalla „Caruso”"
      "02":  
        "en": "W.Kilar „Vocalise” from film „Dziewiąte wrota”"
        "pl": "W.Kilar „Wokaliza” z filmu „Dziewiąte wrota”"
      "03":  
        "en": "F.Lehar „Kiedy skrzypki grają”"
        "pl": "F.Lehar „Kiedy skrzypki grają”"
      "04":  
        "en": "E.Morricone „Nella fantasia” from film „Misja”"
        "pl": "E.Morricone „Nella fantasia” z filmu „Misja”"
      "05":  
        "en": "J.Offenbach „Aria ze śmiechem”"
        "pl": "J.Offenbach „Aria ze śmiechem”"
