title: Sonia Warzyńska
description: Sonia Warzyńska

# Owner info
owner:
  name: Sonia Warzyńska


# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Europe/Warsaw

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink: /:title/