# Header metadata
url: soniawarzynska.com

author: Sonia Warzyńska

description_pl: Solistka Sonia Warzyńska - sopran. Oficjalna strona artystki.
description_en: Soloist Sonia Warzyńska - soprano. Official website of the artist.

og_site_name_pl: Sonia Warzyńska - sopran
og_site_name_en: Sonia Warzyńska - soprano

# Social media
social:
  facebook: https://facebook.com/SoniaWarzynskaSopran
  gplus   : https://plus.google.com/+SoniaWarzynskaSopran
  twitter : https://twitter.com/sonia_warzynska
  youtube : https://youtube.com/SoniaWarzynskaSopran
  
  
# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Europe/Warsaw

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink: /:title/

xxx: 
  yyy: 
    "1": test
    "2": test
    "3": test
	
	
gallery:
  "tarnobrzeg":
    "title":
      "pl": "Tarnobrzeg"
      "en": "Tarnobrzeg"
    "desc":
      "pl": "Jubileusz 40-lecia Państwowej Szkoły Muzycznej w Tarnobrzegu 27.10.2014r"
      "en": "Tarnobrzeg 27.10.2014r"
    "images":
      "01": "tarnobrzeg1"	
      "02": "tarnobrzeg2"	
      "03": "tarnobrzeg3"	