# Header metadata
url: soniawarzynska.com

author: Sonia Warzyńska

description_pl: Solistka Sonia Warzyńska - sopran. Oficjalna strona artystki.
description_en: Soloist Sonia Warzyńska - soprano. Official website of the artist.

og_site_name_pl: Sonia Warzyńska - sopran
og_site_name_en: Sonia Warzyńska - soprano

# Social media
social:
  facebook: https://facebook.com/SoniaWarzynskaSopran
  gplus   : https://plus.google.com/+SoniaWarzynskaSopran
  twitter : https://twitter.com/sonia_warzynska
  youtube : https://youtube.com/SoniaWarzynskaSopran
  
  
# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Europe/Warsaw

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink: /:title/

# Struktura galerii
gallery:
  "bukowno2014":
    "title":
      "pl": "Bukowno"
      "en": "Bukowno"
    "desc":
      "pl": "Koncert w Miejskim Ośrodku Kultury w Bukownie, 14.11.2014r. Wraz z Sylwią Frączek (sopran) i Aleksandrem Bardasau (baryton)"
      "en": "Concert in Municipal Cultural Centere in Bukowno with Sylwia Frączek (soprano) and Aleksandr Bardasau (baritone), 14.11.2014."
    "images":
      "01": "bukowno1"	
      "02": "bukowno2"	
      "03": "bukowno3"	
      "04": "bukowno4"	
      "05": "bukowno5"	
      "06": "bukowno6"	
      "07": "bukowno7"	
      "08": "bukowno8"	

  "tarnobrzeg":
    "title":
      "pl": "Tarnobrzeg"
      "en": "Tarnobrzeg"
    "desc":
      "pl": "Jubileusz 40-lecia Państwowej Szkoły Muzycznej w Tarnobrzegu 27.10.2014r"
      "en": "Tarnobrzeg 27.10.2014r"
    "images":
      "01": "tarnobrzeg1"	
      "02": "tarnobrzeg2"	
      "03": "tarnobrzeg3"

  "wroclaw":
    "title":
      "pl": "Platinum Palace Wrocław"
      "en": "Platinum Palace Wrocław"
    "desc":
      "pl": "Koncert w ramach Aukcji Młodej Sztuki III, Platinum Palace we Wrocławiu, 18.10.2014r."
      "en": "Platinum Palace Wrocław, 18.20.2014r."
    "images":
      "01": "wroclaw1"	
      "02": "wroclaw2"


repertoire:
  "parts":
    "title":
      "pl": Partie
      "en": Parts
    "items":
      "01":
        "en": "W.A.Mozart „Le Nozze di Figaro”: Susanna"
        "pl": "W.A.Mozart „Wesele Figara„: Zuzanna"
      "02":
        "en": "G.F.Händel „Rodelinda”: Rodelinda"
        "pl": "G.F.Händel „Rodelinda”: Rodelinda"
      "03":
        "en": "H.Purcell „The Fairyqueen”: Nyph, Night"
        "pl": "H.Purcell „The Fairyqueen”: Nyph, Night"
      "04":
        "en": "W.A.Mozart „Requiem in d minor”"
        "pl": "W.A.Mozart „Requiem d-moll”"
      "05":
        "en": "W.A.Mozart „Messe in c minor”"
        "pl": "W.A.Mozart „Msza c-moll”"
      "06":
        "en": "J.Haydn „Missa in augustiis”"
        "pl": "J.Haydn „Msza nelsońska”"

  "arias":
    "01":  
        "en": "L.Arditi „Il bacio”"
    "02":
        "en": "J.S.Bach “Heute noch” from “Kaffeekantate”"
    "03":
        "en": "V.Bellini „Eccomi in lieta vesta... Oh, quante volte...” from “Capuleti e i Montecchi” (Julia)"
    "04":
        "en": "G.Bizet “Me voilà seule dans la nuit... Comme autrefois...” from “Les pêcheurs de perles” (Leila)"
    "05":
        "en": "G.Caccini “Amarilli, mia bella”"
    "06":
        "en": "P.Czajkowski “Отчего это прежде не знала” from “Iolanta” (Iolanta)"
    "07":
        "en": "G.Donizetti „Il faut partir” from „La fille du régiment” (Maria)"
    "08":        
        "en": "G.Donizetti „Salut a la France” from „La fille du régiment” (Maria)"
    "09":
        "en": "G.Donizetti “Quel guardo il cavaliere... So anch’io...” from “Don Pasquale” (Norina)"
    "10":
        "en": "G.Donizetti “Regnava nel silenzio... Quando rapito in estasi...” from “Lucia di Lammermoor” (Lucia)"
    "11":
        "en": "A.Dvořak “Měsičku na nebe hlubokem” from “Rusalka” (Rusalka)"
    "12":
        "en": "J.Haydn „Infelice sventurata” from „I due supposti Conti” (Beatrice)"
    "13":
        "en": "G.F.Händel „Tornami z vagheggiar” from „Alcina” (Morgana)"
    "14":
        "en": "G.F.Händel „Piangeró la sorte mia” from „Giulio Cesare” (Cleopatra)"
    "15":
        "en": "G.F.Händel „Lascia ch’io pianga” from „Rinaldo”"
    "16":
        "en": "K.Kurpiński „Wiek kwiecisty prędko płynie...” from „Leśniczy z Kozienickiej Puszczy” (Zośka)"
    "17":
        "en": "K.Kurpiński „Spojrzenia tkliwe, uczucia żywe...” from „Czaromysł” (Wandala)"
    "18":
        "en": "J.Massenet „Obêissons quand leur voix appelle” from „Manon” (Manon)"
    "19":
        "en": "W.A.Mozart „Ach, ich fühl’s” from „Die Zauberflöte” (Pamina)"
    "20":
        "en": "W.A.Mozart „Vedrai, carino” from „Don Giovanni” (Zerlina)"
    "21":
        "en": "W.A.Mozart “Giunse alfin il momento... Deh, vieni, non tardar...” from “Le Nozze di Figaro” (Susanna)"
    "22":
        "en": "W.A.Mozart “Venite inginocchiatevi” from “Le Nozze di Figaro” (Susanna)"
    "23":
        "en": "G.Puccini „O mio babbino caro” from „Gianni Schicchi” (Lauretta)"
    "24":
        "en": "M.Rimski-Korsakow „С подружками по ягоду ходить” from „Снегурочка” (Снегурочка)"
    "25":
        "en": "G.Verdi „Gualtier Maldè... Caro nome...” from “Rigoletto” (Gilda)"
    "26":
        "en": "G.Verdi „Tutte le feste” from „Rigoletto” (Gilda)"
    "27":
        "en": "C.M. von Weber „Kommt ein schlanken...” from “Der Freischütz” (Ännchen)"
    "28":
        "en": "W.Żeleński „Tam orzeł na turniami...” from „Janek” (Bronka)"

  "sacred":
    "01":
      "en": "G.B.Pergolesi „Vidit suum” from „Stabat mater”"
    "02":  
      "en": "J.S.Bach „Quia respexit” from „Magnificat”"
    "03":  
      "en": "J.S.Bach „Er hat uns allen wohlgetan... Aus Liebe will mein Heiland sterben” from “Die Matthäus-Passion”"
    "04":  
      "en": "J.Haydn “Nun beut die Flur das frische Grün” from “Die Schöpfung” (Gabriel)"


  "songs":
    "01":  
      "en": "S.Barber „Puisque tout passe”"
    "02":  
      "en": "F.Chopin „Piosnka litewska”"
    "03":  
      "en": "F.Chopin „Poseł”"
    "04":  
      "en": "F.Chopin „Wiosna”"
    "05":  
      "en": "C.Debussy „Nuit d’étoiles”"
    "06":  
      "en": "E.Granados “El majo discreto”"
    "07":  
      "en": "R.Hahn „Si mes vers avaient des ailes”"
    "08":  
      "en": "M.Karłowicz “Rdzawe liście”"
    "09":  
      "en": "F.Liszt „Oh, quand je dors”"
    "10":  
      "en": "F.Maklakiewicz “A jeśli chcesz zapomnieć”"
    "11":  
      "en": "F.Maklakiewicz “Kocham Cię”"
    "12":  
      "en": "S.Moniuszko “Dumka”"
    "13":  
      "en": "S.Moniuszko „Złota rybka”"
    "14":  
      "en": "S.Niewiadomski „Otwórz, Janku”"
    "15":  
      "en": "S.Niewiadomski „Śmieją się złote łany”"
    "16":  
      "en": "F.Nowowiejski „Pieśń miłosna”"
    "17":  
      "en": "I.J.Paderewski „Gdy ostatnia róża zwiędła” from „4 Songs to Poems by Adam Asnyk”"
    "18":  
      "en": "I.J.Paderewski „Lune froide” from „12 Songs to Poems by Catulle Mendès”"
    "19":  
      "en": "I.J.Paderewski „Moja pieszczotka” from „6  Songs to Poems by Adam Mickiewicz”"
    "20":  
      "en": "I.J.Paderewski „Nad wodą wielką i czystą” from „6 Songs to Poems by Adam Mickiewicz”"
    "21":  
      "en": "I.J.Paderewski „Ton coeur est d’or pur” from „12 Songs to Poems by Catulle Mendès”"
    "22":  
      "en": "P.Perkowski „Uty japońskie” (the whole cycle)"
    "23":  
      "en": "A.Rubinstein „Ночь”"
    "24":  
      "en": "S.Rachmaninow „Полюбилая”"
    "25":  
      "en": "S.Rachmaninow „Здесь хорошо”"
    "26":  
      "en": "R.Schumann “Das Lied der Suleika” from „Liederkreis”"
    "27":  
      "en": "R.Schumann „Die Lotosblume” from „Liederkreis”"
    "28":  
      "en": "R.Schumann „Mondnacht” from „Liederkreis”"
    "29":  
      "en": "J.Szulc „Claire de lune”"
    "30":  
      "en": "K.Szymanowski “ Christkindleins Wiegenlied”"
    "31":  
      "en": "K.Szmanowski „Zielone słowa”"
    "32":  
      "en": "W.Żeleński „Blada róża”"

  "duets":
    "01":  
      "en": "P.Czajkowski „Final scene” from „Eugene Oniegin”"
    "02":  
      "en": "L.Delibes “Flower Duet” from. „Lakmé”"
    "03":  
      "en": "W.A.Mozart Susanna&Conte duet “Crudel, perchè finora” from „Le Nozze di Figaro”"
    "04":  
      "en": "W.A.Mozart Susanna&Figaro duet „Cinque, dieci” from „Le Nozze di Figaro”"
    "05":  
      "en": "W.A.Mozart Susanna&Figaro duet „Se a caso madama” from „Le Nozze di Figaro”"
    "06":  
      "en": "W.A.Mozart Susanna&Marcellina duet „Via resti servita” from „Le Nozze di Figaro”"
    "07":  
      "en": "W.A.Mozart Susanna&Contessa duet „Sull’aria” from „Le Nozze di Figaro”"
    "08":  
      "en": "W.A.Mozart Zerlina&Don Giovanni duet „La ci darem la mano” from „Don Giovanni”"
    "09":  
      "en": "W.A.Mozart Annius&Servillia duet „Ah, perdona al primo affetto” from “Clemenza di Tito”"
    "10":  
      "en": "G.Rossini “Cat’s Duet”"
    "11":  
      "en": "G.Rossini duet „La regata veneziana”"
    "12":  
      "en": "G.Verdi Violetta&Germont duet „Madamigella Valery...” from “Traviata”"

  "others":
    "01":  
      "en": "L.Dalla „Caruso”"
      "pl": "L.Dalla „Caruso”"
    "02":  
      "en": "W.Kilar „Vocalise” from film „Dziewiąte wrota”"
      "pl": "W.Kilar „Wokaliza” z filmu „Dziewiąte wrota”"
    "03":  
      "en": "F.Lehar „Kiedy skrzypki grają”"
      "pl": "F.Lehar „Kiedy skrzypki grają”"
    "04":  
      "en": "E.Morricone „Nella fantasia” from film „Misja”"
      "pl": "E.Morricone „Nella fantasia” z filmu „Misja”"
    "05":  
      "en": "J.Offenbach „Aria ze śmiechem”"
      "pl": "J.Offenbach „Aria ze śmiechem”"


Arie:
L.Arditi „Il bacio”

J.S.Bach “Heute noch” z “Kantaty o kawie”

V.Bellini „Eccomi in lieta vesta... Oh, quante volte...” z opery “Capuleti e i Montecchi” (Julia)

G.Bizet “Me voilà seule dans la nuit... Comme autrefois...” z opery “Poławiacze Pereł” (Leila)

G.Caccini “Amarilli, mia bella”

P.Czajkowski “Отчего это прежде не знала” z op. “Iolanta” (Iolanta)

G.Donizetti „Il faut partir” z opery „Córka pułku” (Maria)

G.Donizetti „Salut a la France” z opery „Córka pułku” (Maria)

G.Donizetti “Quel guardo il cavaliere... So anch’io...” z opery “Don Pasquale” (Norina)

G.Donizetti “Regnava nel silenzio... Quando rapito in estasi...” z opery “Łucja z Lammermoor” (Łucja)

A.Dvořak “Měsičku na nebe hlubokem” z opery “Rusałka” (Rusałka)

J.Haydn „Infelice sventurata” z opery „I due supposti Conti” (Beatrycze)

G.F.Händel „Tornami z vagheggiar” z opery „Alcina” (Morgana)

G.F.Händel „Piangeró la sorte mia” z opery „Juliusz Cezar” (Kleopatra)

G.F.Händel „Lascia ch’io pianga” z opery „Rinaldo”

K.Kurpiński „Wiek kwiecisty prędko płynie...” z opery „Leśniczy z Kozienickiej Puszczy” (Zośka)

K.Kurpiński „Spojrzenia tkliwe, uczucia żywe...” z opery „Czaromysł” (Wandala)

J.Massenet „Obêissons quand leur voix appelle” z opery „Manon” (Manon)

W.A.Mozart „Ach, ich fühl’s” z opery „Czarodziejski flet” (Pamina)

W.A.Mozart „Vedrai, carino” z opery „Don Giovanni” (Zerlina)

W.A.Mozart “Giunse alfin il momento... Deh, vieni, non tardar...” z opery “Wesele Figara” (Zuzanna)

W.A.Mozart “Venite inginocchiatevi” z opery “Wesele Figara” (Zuzanna)

G.Puccini „O mio babbino caro” z opery „Gianni Schicchi” (Lauretta)

M.Rimski-Korsakow „С подружками по ягоду ходить” z opery „Snieguroczka” (Snieguroczka)

G.Verdi „Gualtier Maldè... Caro nome...” z opery “Rigoletto” (Gilda)
G.Verdi „Tutte le feste” z opery „Rigoletto” (Gilda)

C.M. von Weber „Kommt ein schlanken...” z opery “Wolny strzelec” (Anusia)

W.Żeleński „Tam orzeł na turniami...” z opery „Janek” (Bronka)

Arie Sakralne:
G.B.Pergolesi „Vidit suum” z oratorium „Stabat mater”

J.S.Bach „Quia respexit” z „Magnificat”

J.S.Bach „Er hat uns allen wohlgetan... Aus Liebe will mein Heiland sterben” z “Pasji wg św.Mateusza”

J.Haydn “Nun beut die Flur das frische Grün” z oratorium “Stworzenie świata” (Gabriel)

Pieśni:
S.Barber „Puisque tout passe”

F.Chopin „Piosnka litewska”

F.Chopin „Poseł”

F.Chopin „Wiosna”

C.Debussy „Nuit d’étoiles”

E.Granados “El majo discreto”

R.Hahn „Si mes vers avaient des ailes”

M.Karłowicz “Rdzawe liście”

F.Liszt „Oh, quand je dors”

F.Maklakiewicz “A jeśli chcesz zapomnieć”

F.Maklakiewicz “Kocham Cię”

S.Moniuszko “Dumka”

S.Moniuszko „Złota rybka”

S.Niewiadomski „Otwórz, Janku”

S.Niewiadomski „Śmieją się złote łany”

F.Nowowiejski „Pieśń miłosna”

I.J.Paderewski „Gdy ostatnia róża zwiędła” z cyklu „4 pieśni do tekstów Asnyka”

I.J.Paderewski „Lune froide” z cyklu „12 pieśni do słów Mendèsa”

I.J.Paderewski „Moja pieszczotka” z cyklu „6 pieśni do słów Mickiewicza”

I.J.Paderewski „Nad wodą wielką i czystą” z cyklu „6 pieśni do słów Mickiewicza”

I.J.Paderewski „Ton coeur est d’or pur” z cyklu „12 pieśni do słów Mendèsa”

P.Perkowski „Uty japońskie” (cały cykl)

A.Rubinstein „Ночь”

S.Rachmaninow „Полюбилая”

S.Rachmaninow „Здесь хорошо”

R.Schumann “Das Lied der Suleika” z cyklu „Liederkreis”

R.Schumann „Die Lotosblume” z cyklu „Liederkreis”

R.Schumann „Mondnacht” z cyklu „Liederkreis”

J.Szulc „Claire de lune”

K.Szymanowski “Kołysanka Dzieciątka Jezus”

K.Szmanowski „Zielone słowa”

W.Żeleński „Blada róża”

Duety:
P.Czajkowski Scena finałowa z op. „Eugeniusz Oniegin”

L.Delibes duet kwiatów z op. „Lakmé”

W.A.Mozart duet Zuzanny i Hrabiego “Crudel, perchè finora” z op. „Wesele Figara”

W.A.Mozart duet Zuzanny i Figara „Cinque, dieci” z op. „Wesele Figara”

W.A.Mozart duet Zuzanny i Figara „Se a caso madama” z op. „Wesele Figara”

W.A.Mozart duet Zuzanny i Marcelliny „Via resti servita” z op. „Wesele Figara”

W.A.Mozart duet Zuzanny i Hrabiny „Sull’aria” z op. „Wesele Figara”

W.A.Mozart duet Zerliny i Don Giovanniego „La ci darem la mano” z op. „Don Giovanni”

W.A.Mozart duet Anniusa i Servilii „Ah, perdona al primo affetto” z op. „Łaskawość Tytusa”

G.Rossini duet kotów

G.Rossini duet „La regata veneziana”

G.Verdi duet Violetty i Germonta „Madamigella Valery...” z op. “Traviata”
	
